theme: minima
title: CodeWorks Journal
tagline: Learn to Code. Develop your future!
description: My notes and reflections while learning to code
author: CodeWorks
logo: /img/codeworks.png

plugins:
  - jekyll-seo-tag

social:
  name: CodeWorks
  links:
    - https://twitter.com/boisecodeworks
    - https://www.facebook.com/boisecodeworks
    - https://www.linkedin.com/school/boisecodeworks
    - https://github.com/boisecodeworks
