theme: minima
title: CodeWorks Journal
tagline: Learn to Code. Develop your future!
description: My notes and reflections while learning to code
author: CodeWorks
logo: /assets/img/codeworks.png
header_pages:
  - reflections.md
  - notes.md
  - quizes.md
plugins:
  - jekyll-seo-tag
minima:
  skin: dark
social:
  name: CodeWorks
  links:
    - https://twitter.com/boisecodeworks
    - https://www.facebook.com/boisecodeworks
    - https://www.linkedin.com/school/boisecodeworks
    - https://github.com/boisecodeworks
